theme: jekyll-theme-slate
title: Welcome to Bri's page!
description: Visual Basic Applications for Excel has tons of uses and is particularly useful when working with large sets of data. I cover the basic concepts and uses for VBA and I'm gradually working my way up to illsutrating its more complex uses.
